### ISSUE TITLE
Remove support for Rails < 5 and Ruby < 2.5

### ISSUE THREAD

**Issue by skalee** [riboseinc/activeuuid#66]
Let's cut off some ballast. Legacy code means trouble.

There's no point in reintroducing Rails 4.2 support. Although it still receives occasional security updates ([May 2020](https://weblog.rubyonrails.org/2020/5/15/Rails-4-2-11-2-has-been-released/)), it's really old and two major versions behind the latest Rails.

Let's drop support for some oldest Rubies too. There is no point in maintaining compatibility with Ruby 2.3, which has reached its end of life over a year ago (on 2019-03-31), and is causing problems due to incompatibility with current versions of `mysql2` gem. We should drop support for Ruby 2.4 too — although it isn't problematic now, 

There is no good point in maintaining compatibility with Ruby 2.4, which has reached its end of life about two months ago (2020-03-31). Although all works now, we can expect some problems in future, especially with native code in database backends.

Perhaps we should drop support for Ruby 2.5 too, I haven't decided yet. It is still supported, but fairly old and is scheduled to reach its end of life next year (on 2021-03-31). Dropping support now means not having to do it in near future. It's good to do one big breaking change rather than two smaller ones.

### TODO

- [ ] Remove old versions from test matrix.
- [ ] Remove any logic which was for Rails 4 solely.
- [ ] Remove any logic which was for older Rubies solely.
- [ ] Remove support for `mysql` gem (not to be confused with `mysql2`)
- [ ] Bump Ruby and Rails version constraints in the gemspec.
- [ ] Update tools configuration (e.g. Rubocop)
- [ ] Mention in the README that the original gem supports older software.

**Comment by ronaldtse** [comment]
Agree with @skalee , let's do that. Ping @ribose-jeffreylau any objections?

**Comment by skalee** [comment]
Also support for [`mysql`](https://rubygems.org/gems/mysql) gem should be removed. This is a very old adapter gem (last release in 2013) which has been superseded with [`mysql2`](https://rubygems.org/gems/mysql2) gem.

**Comment by ribose-jeffreylau** [comment]
Agreed.
Let's drop support for `mysql` gem as well, like @skalee said.

**Comment by ronaldtse** [comment]
This is somewhat addressed in #71
